export const WISHLIST_CREATE_REQUEST = 'WISHLIST_CREATE_REQUEST';
export const WISHLIST_CREATE_SUCCESS = 'WISHLIST_CREATE_SUCCESS';
export const WISHLIST_CREATE_FAIL = 'WISHLIST_CREATE_FAIL';

export const WISHLIST_DETAILS_REQUEST = 'WISHLIST_DETAILS_REQUEST';
export const WISHLIST_DETAILS_SUCCESS = 'WISHLIST_DETAILS_SUCCESS';
export const WISHLIST_DETAILS_FAIL = 'WISHLIST_DETAILS_FAIL';

export const WISHLIST_PAY_REQUEST = 'WISHLIST_PAY_REQUEST';
export const WISHLIST_PAY_SUCCESS = 'WISHLIST_PAY_SUCCESS';
export const WISHLIST_PAY_FAIL = 'WISHLIST_PAY_FAIL';
export const WISHLIST_PAY_RESET = 'WISHLIST_PAY_RESET';

export const WISHLIST_LIST_MY_REQUEST = 'WISHLIST_LIST_MY_REQUEST';
export const WISHLIST_LIST_MY_SUCCESS = 'WISHLIST_LIST_MY_SUCCESS';
export const WISHLIST_LIST_MY_FAIL = 'WISHLIST_LIST_MY_FAIL';
export const WISHLIST_LIST_MY_RESET = 'WISHLIST_LIST_MY_RESET';

export const WISHLIST_LIST_REQUEST = 'WISHLIST_LIST_REQUEST';
export const WISHLIST_LIST_SUCCESS = 'WISHLIST_LIST_SUCCESS';
export const WISHLIST_LIST_FAIL = 'WISHLIST_LIST_FAIL';
